### ISSUE TITLE
Alabama does not redirect automatically to secure https://alabama.machetessl.org

### ISSUE THREAD

**Issue by nathandrex** [MacheteAdmin/Machete#124]
If you use the URLs:

alabama.machetessl.org
www.alabama.machetessl.org
http://alabama.machetessl.org 
Etc

It goes to the root domain: https://machetessl.org/

**Comment by nathandrex** [comment]
This also seems to be affecting Test too. I'm beginning to believe it has something to do with my deployment environment. Someone else should deploy and test to see if it is corrected.

**Comment by jcii** [comment]
http://alabama.machetessl.org  works. I changed nothing. Not sure what happened in the last 9 months.
